stages:
  - test
  - build
  - deploy

cache:
  paths:
    - bin/

test:syntax:7.1:
  stage: test
  image: php:7.1-cli
  tags:
    - docker
  script:
    - make syntax

test:sniffer:
  stage: test
  image: php:7.1-cli
  tags:
    - docker
  script:
    - make sniff

deploy:mailer:admin:
  stage: deploy
  script:
    - if [ ! -f bin/composer ]; then mkdir bin && curl -sS https://getcomposer.org/installer -o composer-setup.php && php composer-setup.php --install-dir=bin --filename=composer ; fi
    - cd Mailer/
    - ln -s ~/.env.mailer .env
    - ../bin/composer install --optimize-autoloader --verbose --prefer-dist --no-progress --no-interaction --no-suggest --no-dev
    - yarn install && yarn run production
    - rm -fr ./node_modules
    - vendor/bin/dep deploy mailer --revision=$CI_COMMIT_SHA -vvv
  environment:
    name: production/remp2020/mailer
    url: https://mailer.remp2020.com
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master
  dependencies: []

deploy:campaign:admin:
  stage: deploy
  script:
    - if [ ! -f bin/composer ]; then mkdir bin && curl -sS https://getcomposer.org/installer -o composer-setup.php && php composer-setup.php --install-dir=bin --filename=composer ; fi
    - cd Campaign/
    - ln -s ~/.env.campaign .env
    - ../bin/composer install --optimize-autoloader --verbose --prefer-dist --no-progress --no-interaction --no-suggest --no-dev
    - yarn install && yarn run all-production
    - rm -fr ./node_modules
    - vendor/bin/dep deploy campaign --revision=$CI_COMMIT_SHA -vvv
  environment:
    name: production/remp2020/campaign
    url: https://campaign.remp2020.com
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master
  dependencies: []

deploy:beam:admin:
  stage: deploy
  script:
    - if [ ! -f bin/composer ]; then mkdir bin && curl -sS https://getcomposer.org/installer -o composer-setup.php && php composer-setup.php --install-dir=bin --filename=composer ; fi
    - cd Beam/
    - ln -s ~/.env.beam .env
    - ../bin/composer install --optimize-autoloader --verbose --prefer-dist --no-progress --no-interaction --no-suggest --no-dev
    - yarn install && yarn run all-production
    - rm -fr ./node_modules
    - vendor/bin/dep deploy beam --revision=$CI_COMMIT_SHA -vvv
  environment:
    name: production/remp2020/beam
    url: https://beam.remp2020.com
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master
  dependencies: []

deploy:sso:admin:
  stage: deploy
  script:
    - if [ ! -f bin/composer ]; then mkdir bin && curl -sS https://getcomposer.org/installer -o composer-setup.php && php composer-setup.php --install-dir=bin --filename=composer ; fi
    - cd Sso/
    - ln -s ~/.env.sso .env
    - ../bin/composer install --optimize-autoloader --verbose --prefer-dist --no-progress --no-interaction --no-suggest --no-dev
    - yarn install && yarn run production
    - rm -fr ./node_modules
    - vendor/bin/dep deploy sso --revision=$CI_COMMIT_SHA -vvv
  environment:
    name: production/remp2020/sso
    url: https://sso.remp2020.com
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master
  dependencies: []

deploy:mailer:novydenik:
  stage: deploy
  script:
    - >
      curl -X POST
      -F "token=$CI_JOB_TOKEN"
      -F "ref=master"
      -F "variables[REF]=$CI_COMMIT_SHA"
      -F "variables[STAGE]=novydenik/mailer"
      -F "variables[URL]=https://mailer.novydenik.cz"
      https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master
  dependencies: []