stages:
  - test
  - deploy

syntax:7.0:
  stage: test
  image: php:7.0-cli
  tags:
    - docker
  script:
    - make syntax

syntax:7.1:
  stage: test
  image: php:7.1-cli
  tags:
    - docker
  script:
    - make syntax

sniffer:
  stage: test
  image: php:7.0-cli
  tags:
    - docker
  script:
    - make sniff
