stages:
  - test
  - deploy

cache:
  paths:
    - bin/

syntax:7.1:
  stage: test
  image: php:7.1-cli
  tags:
    - docker
  script:
    - make syntax

sniffer:
  stage: test
  image: php:7.1-cli
  tags:
    - docker
  script:
    - make sniff

mailer/dennikn:
  stage: deploy
  script:
  - >
    curl -X POST
    -F "token=$CI_JOB_TOKEN"
    -F "ref=master"
    -F "variables[REF]=$CI_COMMIT_SHA"
    -F "variables[STAGE]=dennikn/mailer"
    -F "variables[URL]=https://mailer.remp2020.com"
    https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master

campaign/dennikn:
  stage: deploy
  script:
  - >
    curl -X POST
    -F "token=$CI_JOB_TOKEN"
    -F "ref=master"
    -F "variables[REF]=$CI_COMMIT_SHA"
    -F "variables[STAGE]=dennikn/campaign"
    -F "variables[URL]=https://campaign.remp2020.com"
    https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master
  dependencies: []

beam/dennikn:
  stage: deploy
  script:
  - >
    curl -X POST
    -F "token=$CI_JOB_TOKEN"
    -F "ref=master"
    -F "variables[REF]=$CI_COMMIT_SHA"
    -F "variables[STAGE]=dennikn/beam"
    -F "variables[URL]=https://beam.remp2020.com"
    https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master
  dependencies: []

sso/dennikn:
  stage: deploy
  script:
  - >
    curl -X POST
    -F "token=$CI_JOB_TOKEN"
    -F "ref=master"
    -F "variables[REF]=$CI_COMMIT_SHA"
    -F "variables[STAGE]=dennikn/sso"
    -F "variables[URL]=https://sso.remp2020.com"
    https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master
  dependencies: []

mailer/novydenik:
  stage: deploy
  script:
    - >
      curl -X POST
      -F "token=$CI_JOB_TOKEN"
      -F "ref=master"
      -F "variables[REF]=$CI_COMMIT_SHA"
      -F "variables[STAGE]=novydenik/mailer"
      -F "variables[URL]=https://mailer.novydenik.cz"
      https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master
  dependencies: []

campaign/novydenik:
  stage: deploy
  script:
  - >
    curl -X POST
    -F "token=$CI_JOB_TOKEN"
    -F "ref=master"
    -F "variables[REF]=$CI_COMMIT_SHA"
    -F "variables[STAGE]=novydenik/campaign"
    -F "variables[URL]=https://campaign.novydenik.cz"
    https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
  - remp2020
  - deploy
  only:
  - master
  dependencies: []

beam/novydenik:
  stage: deploy
  script:
  - >
    curl -X POST
    -F "token=$CI_JOB_TOKEN"
    -F "ref=master"
    -F "variables[REF]=$CI_COMMIT_SHA"
    -F "variables[STAGE]=novydenik/beam"
    -F "variables[URL]=https://beam.novydenik.cz"
    https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
  - remp2020
  - deploy
  only:
  - master
  dependencies: []

sso/novydenik:
  stage: deploy
  script:
  - >
    curl -X POST
    -F "token=$CI_JOB_TOKEN"
    -F "ref=master"
    -F "variables[REF]=$CI_COMMIT_SHA"
    -F "variables[STAGE]=novydenik/sso"
    -F "variables[URL]=https://sso.novydenik.cz"
    https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
  - remp2020
  - deploy
  only:
  - master
  dependencies: []

"mailer/denikncz 🇨🇿":
  stage: deploy
  script:
    - >
      curl -X POST
      -F "token=$CI_JOB_TOKEN"
      -F "ref=master"
      -F "variables[REF]=$CI_COMMIT_SHA"
      -F "variables[STAGE]=denikncz/mailer"
      -F "variables[URL]=https://mailer.denikn.cz"
      https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master
  dependencies: []

"campaign/denikncz 🇨🇿":
  stage: deploy
  script:
  - >
    curl -X POST
    -F "token=$CI_JOB_TOKEN"
    -F "ref=master"
    -F "variables[REF]=$CI_COMMIT_SHA"
    -F "variables[STAGE]=denikncz/campaign"
    -F "variables[URL]=https://campaign.denikn.cz"
    https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
  - remp2020
  - deploy
  only:
  - master
  dependencies: []

"beam/denikncz 🇨🇿":
  stage: deploy
  script:
  - >
    curl -X POST
    -F "token=$CI_JOB_TOKEN"
    -F "ref=master"
    -F "variables[REF]=$CI_COMMIT_SHA"
    -F "variables[STAGE]=denikncz/beam"
    -F "variables[URL]=https://beam.denikn.cz"
    https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
  - remp2020
  - deploy
  only:
  - master
  dependencies: []

"sso/denikncz 🇨🇿":
  stage: deploy
  script:
  - >
    curl -X POST
    -F "token=$CI_JOB_TOKEN"
    -F "ref=master"
    -F "variables[REF]=$CI_COMMIT_SHA"
    -F "variables[STAGE]=denikncz/sso"
    -F "variables[URL]=https://sso.denikn.cz"
    https://gitlab.com/api/v4/projects/7413363/trigger/pipeline
  when: manual
  tags:
  - remp2020
  - deploy
  only:
  - master
  dependencies: []