stages:
  - test
  - deploy

syntax:7.0:
  stage: test
  image: php:7.0-cli
  tags:
    - docker
  script:
    - find app bin bootstrap config database -name "*.php" -print0 | xargs -0 -n1 -P8 php -l

syntax:7.1:
  stage: test
  image: php:7.1-cli
  tags:
    - docker
  script:
    - find app bin bootstrap config database -name "*.php" -print0 | xargs -0 -n1 -P8 php -l

sniffer:
  stage: test
  image: php:7.0-cli
  tags:
    - docker
  script:
    - make sniff
