stages:
  - test
  - deploy

cache:
  paths:
    - bin/

syntax:7.0:
  stage: test
  image: php:7.0-cli
  tags:
    - docker
  script:
    - make syntax

syntax:7.1:
  stage: test
  image: php:7.1-cli
  tags:
    - docker
  script:
    - make syntax

sniffer:
  stage: test
  image: php:7.0-cli
  tags:
    - docker
  script:
    - make sniff

deploy:production:mailer:
  stage: deploy
  script:
    - if [ ! -f bin/composer ]; then mkdir bin && curl -sS https://getcomposer.org/installer -o composer-setup.php && php composer-setup.php --install-dir=bin --filename=composer ; fi
    - bin/composer global require deployer/deployer:^5.0 --verbose --prefer-dist --no-progress --no-interaction
    - cd Mailer/
    - ~/.composer/vendor/bin/dep deploy mailer --revision=$CI_COMMIT_SHA -vvv
  variables:
    # GIT_STRATEGY: none
  environment:
    name: production/remp2020/mailer
    url: https://mailer.remp2020.com
  when: manual
  tags:
    - remp2020
    - deploy
  only:
    - master