version: "3"

# see .env file for docker-compose ENV variables required for proper run

services:
  nginx:
    image: "nginx:stable"
    volumes:
      - ".:/var/www/html:rw"
      - "./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"
    restart: "unless-stopped"
    networks:
      default:
        aliases:
          - "campaign.remp.press"
          - "mailer.remp.press"
          - "sso.remp.press"
          - "beam.remp.press"
          - "tracker.beam.remp.press"
          - "segments.beam.remp.press"
          - "grafana.beam.remp.press"
          - "mailhog.remp.press"
          - "kibana.beam.remp.press"

  mysql:
    image: "mysql:5.7" # minimal 5.7.8
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "./Docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-character-set-client-handshake"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "secret"
    restart: "unless-stopped"

  redis:
    image: "redis:3.2"
    volumes:
      - "redis-data:/data"

  mailhog:
    image: "mailhog/mailhog:v1.0.0"
    environment:
      MH_HOSTNAME: "mailhog.remp.press"

  adminer:
    build: "./Docker/php"
    volumes:
      - ".:/var/www/html:rw"

  # campaign

  campaign:
    build: "./Docker/php"
    environment:
      APP_NAME: "Campaign"
      PHP_IDE_CONFIG: "serverName=campaign.remp.press"
    domainname: "campaign.remp.press"
    hostname: "campaign"
    volumes:
      - "./Campaign:/var/www/html/Campaign:rw"
      - "./Composer:/var/www/html/Composer:rw"
      - "./Package:/var/www/html/Package:rw"
    depends_on:
      - "nginx"
      - "mysql"
    restart: "unless-stopped"

  # mailer

  mailer:
    domainname: "mailer.remp.press"
    hostname: "mailer"
    environment:
      APP_NAME: "Mailer"
      PHP_IDE_CONFIG: "serverName=mailer.remp.press"
    build: "./Docker/php"
    volumes:
      - "./Mailer:/var/www/html/Mailer:rw"
      - "./Composer:/var/www/html/Composer:rw"
      - "./Package:/var/www/html/Package:rw"
    depends_on:
      - "nginx"
      - "mysql"
      - "redis"
      - "mailhog"
    restart: "unless-stopped"

  # sso

  sso:
    build: "./Docker/php"
    environment:
      APP_NAME: "Sso"
      PHP_IDE_CONFIG: "serverName=sso.remp.press"
    domainname: "sso.remp.press"
    hostname: "sso"
    volumes:
      - "./Sso:/var/www/html/Sso:rw"
      - "./Composer:/var/www/html/Composer:rw"
      - "./Package:/var/www/html/Package:rw"
    depends_on:
      - "nginx"
      - "mysql"
    restart: "unless-stopped"

  # beam

  beam:
    domainname: "beam.remp.press"
    hostname: "beam"
    build: "./Docker/php"
    environment:
      APP_NAME: "Beam"
      PHP_IDE_CONFIG: "serverName=beam.remp.press"
    volumes:
      - "./Beam:/var/www/html/Beam:rw"
      - "./Composer:/var/www/html/Composer:rw"
      - "./Package:/var/www/html/Package:rw"
    depends_on:
      - "nginx"
      - "mysql"
    restart: "unless-stopped"

  kafka:
    build: "./Docker/kafka"
    environment:
      ADVERTISED_HOST: "kafka"
      ADVERTISED_PORT: "9092"
      CREATE_TOPICS: "beam_events:1:1"
    ports:
      - "9092:9092"
    volumes:
      - "kafka-data:/data"

  influxdb:
    image: "influxdb:1.4"
    volumes:
      - "influxdb-data:/var/lib/influxdb"
    environment:
      INFLUXDB_DATA_MAX_VALUES_PER_TAG: 0
      INFLUXDB_DATA_MAX_SERIES_PER_DATABASE: 0
    ports:
      - "8098:8086"
    restart: "unless-stopped"

  telegraf:
    build: "./Docker/telegraf"
    volumes:
      - "./Docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    depends_on:
      - "influxdb"
      - "kafka"
      - "elasticsearch"
    restart: "unless-stopped"

  grafana:
    image: "grafana/grafana"
    volumes:
      - "grafana-data:/var/lib/grafana"
    restart: "unless-stopped"

  elasticsearch:
    build: "./Docker/elasticsearch"
    ports:
      - "9200:9200"
    volumes:
      - "./Docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "elastic-data:/usr/share/elasticsearch/data"

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.2.2"

  beam_tracker:
    build: "./Beam/go/cmd/tracker"
    depends_on:
      - "kafka"
    ports:
      - "8091:8081"
    restart: "unless-stopped"

  beam_segments:
    build: "./Beam/go/cmd/segments"
    depends_on:
      - "influxdb"
    ports:
      - "8092:8082"
    restart: "unless-stopped"

volumes:
  influxdb-data:
    driver: "local"
  kafka-data:
    driver: "local"
  mysql-data:
    driver: "local"
  redis-data:
    driver: "local"
  grafana-data:
    driver: "local"
  elastic-data:
    driver: "local"

networks:
  default:
