version: "3"

services:
  campaign:
    build: "./Docker/php"
    volumes:
      - .:/var/www/html:rw
    env_file: ./Campaign/.env
    restart: "unless-stopped"

  mailer:
    build: "./Docker/php"
    volumes:
      - .:/var/www/html:rw
    env_file: ./Mailer/.env
    restart: "unless-stopped"

  nginx:
    image: "nginx:stable"
    volumes:
      - .:/var/www/html:rw
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    environment:
      NGINX_HOST: "predplatne"
      NGINX_PORT: "80"
    restart: "unless-stopped"

  kafka:
    build: "./Docker/kafka"
    environment:
        ADVERTISED_HOST: "kafka"
        ADVERTISED_PORT: "9092"
        CREATE_TOPICS: "beam_events:1:1"
    ports:
        - "9092"
        - "2181"
    volumes:
        - "kafka-data:/data"

  influxdb:
    image: "influxdb:1.2"
    volumes:
      - "influxdb-data:/var/lib/influxdb"
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: "unless-stopped"

  telegraf:
    build: "./Docker/telegraf"
    volumes:
      - "./Docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    depends_on:
      - "influxdb"
      - "kafka"
    restart: "unless-stopped"

volumes:
  influxdb-data:
    driver: "local"
  kafka-data:
    driver: "local"
  mysql-data:
    driver: "local"