version: "3"

services:
  nginx:
    image: "nginx:stable"
    volumes:
      - ".:/var/www/html:rw"
      - "./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"
    restart: "unless-stopped"

  redis:
   image: "redis:3.2"
   volumes:
     - "redis-data:/data"

  mailhog:
   image: "mailhog/mailhog:v1.0.0"
   environment:
     MH_HOSTNAME: "mailhog.remp.app"

  adminer:
    build: "./Docker/php"
    volumes:
      - ".:/var/www/html:rw"
    depends_on:
      - "nginx"

  # campaign

  campaign:
    build: "./Docker/php"
    volumes:
      - ".:/var/www/html:rw"
      - "composer-data:/composer/cache:rw"
    depends_on:
      - "campaign_mysql"
      - "nginx"
    extra_hosts:
      - "crm.app:192.168.99.100"
      - "sso.remp.app:192.168.99.100"
    restart: "unless-stopped"

  campaign_mysql:
    image: "mysql:8.0"
    volumes:
      - "mysql-data-campaign:/var/lib/mysql"
    ports:
      - "3311:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-character-set-client-handshake"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "remp_campaign"
    restart: "unless-stopped"

  # mailer

  mailer:
   extra_hosts:
     - "crm.app:192.168.99.100"
     - "sso.remp.app:192.168.99.100"
   build: "./Docker/php"
   volumes:
     - ".:/var/www/html:rw"
     - "composer-data:/composer/cache:rw"
   depends_on:
     - "mailer_mysql"
     - "nginx"
     - "redis"
     - "mailhog"
   restart: "unless-stopped"

  mailer_mysql:
   image: "mysql:8.0"
   volumes:
     - "mysql-data-mailer:/var/lib/mysql"
   ports:
     - "3312:3306"
   command:
     - "--character-set-server=utf8mb4"
     - "--collation-server=utf8mb4_unicode_ci"
     - "--skip-character-set-client-handshake"
   environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: "no"
     MYSQL_ROOT_PASSWORD: "secret"
     MYSQL_DATABASE: "remp_mailer"
   restart: "unless-stopped"

  # sso

  sso:
   build: "./Docker/php"
   volumes:
     - ".:/var/www/html:rw"
     - "composer-data:/composer/cache:rw"
     - $SSH_AUTH_SOCK:/tmp/ssh-agent
   environment:
     SSH_AUTH_SOCK: /tmp/ssh-agent
   depends_on:
     - "nginx"
     - "sso_mysql"
   restart: "unless-stopped"

  sso_mysql:
   image: "mysql:8.0"
   volumes:
     - "mysql-data-sso:/var/lib/mysql"
   ports:
     - "3314:3306"
   command:
     - "--character-set-server=utf8mb4"
     - "--collation-server=utf8mb4_unicode_ci"
     - "--skip-character-set-client-handshake"
   environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: "no"
     MYSQL_ROOT_PASSWORD: "secret"
     MYSQL_DATABASE: "remp_sso"
   restart: "unless-stopped"

  # beam

  beam:
    extra_hosts:
     - "sso.remp.app:192.168.99.100"
    build: "./Docker/php"
    volumes:
      - ".:/var/www/html:rw"
      - "composer-data:/composer/cache:rw"
    depends_on:
      - "beam_mysql"
      - "nginx"
    environment:
      DB_DATABASE: "remp_beam"
      DB_USERNAME: "root"
      DB_PASSWORD: "secret"
    restart: "unless-stopped"

  beam_mysql:
    image: "mysql:8.0"
    volumes:
      - "mysql-data-beam:/var/lib/mysql"
    ports:
      - "3313:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-character-set-client-handshake"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "remp_beam"
    restart: "unless-stopped"

  kafka:
   build: "./Docker/kafka"
   environment:
     ADVERTISED_HOST: "kafka"
     ADVERTISED_PORT: "9092"
     CREATE_TOPICS: "beam_events:1:1"
   ports:
     - "9092"
     - "2181"
   volumes:
     - "kafka-data:/data"

  influxdb:
   image: "influxdb:1.2"
   volumes:
     - "influxdb-data:/var/lib/influxdb"
   ports:
     - "8083:8083"
     - "8086:8086"
   environment:
     INFLUXDB_DATA_MAX_VALUES_PER_TAG: 0 # unlimited due to user_id being a tag (for grouping by)
   restart: "unless-stopped"

  telegraf:
   build: "./Docker/telegraf"
   volumes:
     - "./Docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
   depends_on:
     - "influxdb"
     - "kafka"
   restart: "unless-stopped"

  beam_tracker:
   build: "./Beam/go/cmd/tracker"
   depends_on:
     - "kafka"
   environment:
     TRACKER_BROKER_ADDR: "kafka:9092"
     TRACKER_ADDR: ":8081"
   ports:
     - "8081:8081"
   restart: "unless-stopped"

  beam_segments:
     build: "./Beam/go/cmd/segments"
     depends_on:
       - "influxdb"
     environment:
       BEAM_SEGMENTS_ADDR: ":8082"
     ports:
       - "8082:8082"
     restart: "unless-stopped"

volumes:
  influxdb-data:
    driver: "local"
  kafka-data:
    driver: "local"
  mysql-data-campaign:
    driver: "local"
  mysql-data-mailer:
    driver: "local"
  mysql-data-beam:
    driver: "local"
  mysql-data-sso:
    driver: "local"
  redis-data:
    driver: "local"
  composer-data:
    driver: "local"