version: '3'

services:

    # php-related containers

    nginx:
        image: "nginx:stable"
        volumes:
          - .:/var/www/html:rw
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
          - "8080:80"
        restart: "unless-stopped"

    mysql:
        image: "mysql:5.7"
        volumes:
          - mysql-data:/var/lib/mysql
        ports:
          - "3306:3306"
        command:
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci
          - --skip-character-set-client-handshake
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "no"
          MYSQL_ROOT_PASSWORD: "secret"
          MYSQL_DATABASE: "beam_admin"
        restart: "unless-stopped"

    admin-fpm:
        build: "."
        volumes:
          - .:/var/www/html:rw
        env_file: .env
        restart: "unless-stopped"

    # golang-related containers

    beam:
        build: "go/cmd/tracker"
        depends_on:
            - "kafka"
            - "zookeeper"
        environment:
            BEAM_BROKER_ADDR: "kafka:9092"
            BEAM_TRACKER_ADDR: ":8081"
        ports:
            - "8081:8081"
        restart: "unless-stopped"

    zookeeper:
        image: "zookeeper:3.4"
        ports:
            - "2181:2181"

    kafka:
        build: "docker/kafka"
        depends_on:
            - "zookeeper"
        ports:
            - "9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_CREATE_TOPICS: "beam_events:1:1"
            ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"
        volumes:
            - "kafka-data:/data"

    influxdb:
        image: "influxdb:1.2-alpine"
        volumes:
            - "influxdb-data:/var/lib/influxdb"
        ports:
            - "8083:8083"
            - "8086:8086"
        restart: "unless-stopped"

    telegraf:
        build: "docker/telegraf"
        depends_on:
            - "influxdb"
            - "zookeeper"
            - "kafka"
        restart: "unless-stopped"

volumes:
    influxdb-data:
        driver: "local"
    kafka-data:
        driver: "local"
    mysql-data:
        driver: "local"
