version: '3'

services:
    beam:
        build: "cmd/beam"
        depends_on:
            - "kafka"
            - "zookeeper"
        environment:
            BEAM_BROKER_ADDR: "kafka:9092"
            BEAM_ADDR: ":8081"
        ports:
            - "8081:8081"
        restart: "unless-stopped"

    zookeeper:
        image: "zookeeper:3.4"
        ports:
            - "2181:2181"

    kafka:
        image: "wurstmeister/kafka"
        depends_on:
            - "zookeeper"
        ports:
            - "9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_CREATE_TOPICS: "beam_events:1:1"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"

    influxdb:
        image: "influxdb:1.2-alpine"
        volumes:
            - "influxdb-data:/var/lib/influxdb"
        ports:
            - "8083:8083"
            - "8086:8086"
        restart: "unless-stopped"

    telegraf:
        image: "telegraf:1.2-alpine"
        depends_on:
            - "influxdb"
            - "zookeeper"
            - "kafka"
        volumes:
            - "./docker/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
        restart: "unless-stopped"

volumes:
    influxdb-data:
        driver: "local"